rules:
  no-restricted-imports:
    - error
    - patterns:
        - group:
            - lodash/*
            - lodash.*
            - lodash-es/*
            - '!lodash/fp'
          message: Import from 'lodash-es' instead
        - group:
            - microfrontends/*
            - '!microfrontends/ChildAppMounter'
        - group:
            - modules/45-dashboards/*
            - modules/50-assessments/*
            - modules/60-code/*
            - modules/70-pipeline/*
            - modules/72-freeze-windows/*
            - modules/72-templates-library/*
            - modules/72-triggers/*
            - modules/75-cd/*
            - modules/75-ce/*
            - modules/75-cet/*
            - modules/75-cf/*
            - modules/75-chaos/*
            - modules/75-ci/*
            - modules/75-idp/*
            - modules/75-ssca/*
            - modules/85-cv/*
            - modules/85-iacm/*
            - modules/85-sto/*
            - modules/90-gitops/*
            - '@dashboards/*'
            - '@assessments/*'
            - '@code/*'
            - '@pipeline/*'
            - '@freeze-windows/*'
            - '@templates-library/*'
            - '@triggers/*'
            - '@cd/*'
            - '@ce/*'
            - '@cet/*'
            - '@cf/*'
            - '@chaos/*'
            - '@ci/*'
            - '@idp/*'
            - '@ssca/*'
            - '@cv/*'
            - '@iacm/*'
            - '@sto/*'
            - '@gitops/*'
          message: Import from higher layer modules is not allowed
      paths:
        - lodash
        - name: js-yaml
          message: Please use methods from @common/utils/YamlHelperMethods instead of using js-yaml
        - name: yaml
          importNames:
            - stringify
          message: Please use yamlStringify from @common/utils/YamlHelperMethods instead of this
        - name: react-router
          message: import from "react-router-dom" instead
        - name: microfrontends
          message: Import from 'microfrontends' is only allowed in child apps
        - name: '@harness/uicore'
          importNames:
            - Color
            - FontVariation
            - Intent
            - Spacing
          message: import from "@harness/design-system" instead
