kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: Ivan
apiVersion: backstage.io/v1alpha1
metadata:
  name: BitBucketService
  tags: []
  annotations:
    harness.io/cd-serviceId: BitBucketService
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/default/projects/Ivan/details

