kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: DevXGitSyncProWCuK
apiVersion: backstage.io/v1alpha1
metadata:
  name: "n"
  tags: []
  annotations:
    harness.io/cd-serviceId: "n"
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/DevXGitSyncOrg1caK/projects/DevXGitSyncProWCuK/details

