kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: sonytest1
apiVersion: backstage.io/v1alpha1
metadata:
  name: qatesting-sonytest1-serv2
  tags: []
  annotations:
    harness.io/cd-serviceId: serv2
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/qatesting/projects/sonytest1/details

