kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: ASG
apiVersion: backstage.io/v1alpha1
metadata:
  name: Asg_Order_App
  tags: []
  annotations:
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/Arvind/projects/ASG/details
    harness.io/cd-serviceId: Asg_Order_App

