kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: Depanshu_gitx
apiVersion: backstage.io/v1alpha1
metadata:
  name: default-Depanshu_gitx-s1
  tags: []
  annotations:
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/default/projects/Depanshu_gitx/details
    harness.io/cd-serviceId: s1

