kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: proj
apiVersion: backstage.io/v1alpha1
metadata:
  name: org_1-proj-svc
  tags: []
  annotations:
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/org_1/projects/proj/details
    harness.io/cd-serviceId: svc

