kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: CIGANewDX
apiVersion: backstage.io/v1alpha1
metadata:
  name: sdfdfds
  tags: []
  annotations:
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/AaTestOrg/projects/CIGANewDX/details
    harness.io/cd-serviceId: sdfdfds

