kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: CDDashboard
apiVersion: backstage.io/v1alpha1
metadata:
  name: simpleService
  tags: []
  annotations:
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/default/projects/CDDashboard/details
    harness.io/cd-serviceId: simpleService

