kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: Eric
apiVersion: backstage.io/v1alpha1
metadata:
  name: varTestSrvc
  tags: []
  annotations:
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/default/projects/Eric/details
    harness.io/cd-serviceId: varTestSrvc

