extends:
  - './.eslintrc.yml'
rules:
  '@typescript-eslint/no-explicit-any': 2
  '@typescript-eslint/explicit-function-return-type': 2
  'react/display-name': 2
  '@typescript-eslint/no-non-null-assertion': 2
  'duplicate-data-tooltip-id': 2
  'no-only-tests': 2
