rules:
  no-restricted-imports:
    - error
    - patterns:
        - lodash.*
        - microfrontends/*
        - '!microfrontends/ChildAppMounter'
        - modules/18-audit-trail/*
        - modules/20-rbac/*
        - modules/23-default-settings/*
        - modules/25-governance/*
        - modules/28-et/*
        - modules/30-delegates/*
        - modules/30-secrets/*
        - modules/31-filestore/*
        - modules/31-variables/*
        - modules/33-auth-settings/*
        - modules/35-connectors/*
        - modules/35-user-profile/*
        - modules/40-gitsync/*
        - modules/45-dashboards/*
        - modules/45-projects-orgs/*
        - modules/60-scm/*
        - modules/70-pipeline/*
        - modules/72-freeze-windows/*
        - modules/72-templates-library/*
        - modules/72-triggers/*
        - modules/75-cd/*
        - modules/75-ce/*
        - modules/75-cf/*
        - modules/75-chaos/*
        - modules/75-ci/*
        - modules/85-cv/*
        - modules/85-sto-steps/*
        - modules/90-gitops/*
        - '@audit-trail/*'
        - '@rbac/*'
        - '@default-settings/*'
        - '@governance/*'
        - '@et/*'
        - '@delegates/*'
        - '@secrets/*'
        - '@filestore/*'
        - '@variables/*'
        - '@auth-settings/*'
        - '@connectors/*'
        - '@user-profile/*'
        - '@gitsync/*'
        - '@dashboards/*'
        - '@projects-orgs/*'
        - '@scm/*'
        - '@pipeline/*'
        - '@freeze-windows/*'
        - '@templates-library/*'
        - '@triggers/*'
        - '@cd/*'
        - '@ce/*'
        - '@cf/*'
        - '@chaos/*'
        - '@ci/*'
        - '@cv/*'
        - '@sto-steps/*'
        - '@gitops/*'
      paths:
        - lodash
        - name: js-yaml
          message: Please use methods from @common/utils/YamlHelperMethods instead of using js-yaml
        - name: yaml
          importNames:
            - stringify
          message: Please use yamlStringify from @common/utils/YamlHelperMethods instead of this
        - name: react-router
          message: import from "react-router-dom" instead
        - name: microfrontends
          message: Import from 'microfrontends' is only allowed in child apps
        - name: '@wings-software/uicore'
          importNames:
            - Color
            - FontVariation
            - Intent
            - Spacing
          message: import from "@harness/design-system" instead
