apiVersion: v1
kind: Service
metadata:
  name: next-gen-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "next-gen-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetport }}
  selector:
    {{- include "next-gen-ui.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
