/*
 * Copyright 2023 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */

/* Generated by restful-react */

import React from 'react'
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react'

import { getConfig } from '../config'
export const SPEC_VERSION = '0.1.0'
/**
 * login_BadGateway_response_body result type (default view)
 */
export interface DevLoginBadGatewayResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * login_BadRequest_response_body result type (default view)
 */
export interface DevLoginBadRequestResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * login_Forbidden_response_body result type (default view)
 */
export interface DevLoginForbiddenResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * login_InternalServer_response_body result type (default view)
 */
export interface DevLoginInternalServerResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * login_NotFound_response_body result type (default view)
 */
export interface DevLoginNotFoundResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

export interface DevLoginRequestBody {
  /**
   * Password
   */
  password: string
}

/**
 * login_Unauthorized_response_body result type (default view)
 */
export interface DevLoginUnauthorizedResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * processsbom_BadGateway_response_body result type (default view)
 */
export interface SbomprocessorProcesssbomBadGatewayResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * processsbom_BadRequest_response_body result type (default view)
 */
export interface SbomprocessorProcesssbomBadRequestResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * processsbom_Forbidden_response_body result type (default view)
 */
export interface SbomprocessorProcesssbomForbiddenResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * processsbom_InternalServer_response_body result type (default view)
 */
export interface SbomprocessorProcesssbomInternalServerResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * processsbom_NotFound_response_body result type (default view)
 */
export interface SbomprocessorProcesssbomNotFoundResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * A sbom process request on sscs
 */
export interface SbomprocessorProcesssbomRequestBody {
  /**
   * name of the package
   */
  AccountID?: string
  /**
   * name of the package
   */
  ArtifactID?: string
  /**
   * BuildURL
   */
  BuildURL?: string
  /**
   * stage name where sbom is generated
   */
  Format?: string
  /**
   * name of the package
   */
  PipelineExecutionID?: string
  /**
   * name of the package
   */
  PipelineIdentifier?: string
  /**
   * name of the Project
   */
  ProjectIdentifier?: string
  /**
   * name of the package
   */
  SbomUrl?: string
  /**
   * name of the package
   */
  SequenceId?: string
  /**
   * name of the Stage
   */
  StageIdentifier?: string
  /**
   * name of the package
   */
  Tool?: string
}

/**
 * processsbom_Unauthorized_response_body result type (default view)
 */
export interface SbomprocessorProcesssbomUnauthorizedResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * find_BadGateway_response_body result type (default view)
 */
export interface SearchFindBadGatewayResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * find_BadRequest_response_body result type (default view)
 */
export interface SearchFindBadRequestResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * find_Forbidden_response_body result type (default view)
 */
export interface SearchFindForbiddenResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * find_InternalServer_response_body result type (default view)
 */
export interface SearchFindInternalServerResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * find_NotFound_response_body result type (default view)
 */
export interface SearchFindNotFoundResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

export interface SearchFindResponseBody {
  packageReferences: PackageReferenceResponseBody[]
}

/**
 * find_Unauthorized_response_body result type (default view)
 */
export interface SearchFindUnauthorizedResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * findany_BadGateway_response_body result type (default view)
 */
export interface SearchFindanyBadGatewayResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * findany_BadRequest_response_body result type (default view)
 */
export interface SearchFindanyBadRequestResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * findany_Forbidden_response_body result type (default view)
 */
export interface SearchFindanyForbiddenResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * findany_InternalServer_response_body result type (default view)
 */
export interface SearchFindanyInternalServerResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * findany_NotFound_response_body result type (default view)
 */
export interface SearchFindanyNotFoundResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

export interface SearchFindanyRequestBody {
  /**
   * Harness ExecutionIdentifier ID
   */
  ExecutionIdentifier?: string
  /**
   * Harness pipeline ID
   */
  PipelineIdentifier?: string
  packageIdentifiers: PackageIdentifierRequestBody[]
}

export interface SearchFindanyResponseBody {
  packageReferences: PackageReferenceResponseBody[]
}

/**
 * findany_Unauthorized_response_body result type (default view)
 */
export interface SearchFindanyUnauthorizedResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * health_BadGateway_response_body result type (default view)
 */
export interface SystemHealthBadGatewayResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * health_InternalServer_response_body result type (default view)
 */
export interface SystemHealthInternalServerResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * version_BadGateway_response_body result type (default view)
 */
export interface SystemVersionBadGatewayResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

/**
 * version_InternalServer_response_body result type (default view)
 */
export interface SystemVersionInternalServerResponseBody {
  /**
   * Is the error a server-side fault?
   */
  fault: boolean
  /**
   * ID is a unique identifier for this particular occurrence of the problem.
   */
  id: string
  /**
   * Message is a human-readable explanation specific to this occurrence of the problem.
   */
  message: string
  /**
   * Name is the name of this class of errors.
   */
  name: string
  /**
   * Is the error temporary?
   */
  temporary: boolean
  /**
   * Is the error a timeout?
   */
  timeout: boolean
}

export interface SystemVersionResponseBody {
  /**
   * Build identifier
   */
  commit: string
  /**
   * Version number
   */
  version: string
}

/**
 * A package identifier
 */
export interface PackageIdentifierRequestBody {
  /**
   * name of the package
   */
  name?: string
}

/**
 * A package search request on sscs
 */
export interface PackageReferenceResponseBody {
  /**
   * name of the package
   */
  AccountName?: string
  /**
   * Source ID associated with this connection source
   */
  ArtifactName?: string
  /**
   * Source ID associated with this connection source
   */
  BuildURL?: string
  /**
   * name of the package
   */
  Originator?: string
  /**
   * name of the package
   */
  PipelineIdentifier?: string
  /**
   * Source ID associated with this connection source
   */
  SBOMURL?: string
  /**
   * name of the package
   */
  SequenceId?: string
  /**
   * stage name where sbom is generated
   */
  StageName?: string
  /**
   * name of the package
   */
  VersionInfo?: string
  /**
   * name of the package
   */
  name?: string
}

export interface DevLoginQueryParams {
  /**
   * Harness account ID
   */
  accountIdentifier: string
  /**
   * Harness organization ID
   */
  orgIdentifier: string
  /**
   * Harness project ID
   */
  projectIdentifier: string
}

export type DevLoginProps = Omit<
  MutateProps<
    string,
    | DevLoginBadRequestResponseBody
    | DevLoginUnauthorizedResponseBody
    | DevLoginForbiddenResponseBody
    | DevLoginNotFoundResponseBody
    | DevLoginInternalServerResponseBody
    | DevLoginBadGatewayResponseBody,
    DevLoginQueryParams,
    DevLoginRequestBody,
    void
  >,
  'path' | 'verb'
>

export const DevLogin = (props: DevLoginProps) => (
  <Mutate<
    string,
    | DevLoginBadRequestResponseBody
    | DevLoginUnauthorizedResponseBody
    | DevLoginForbiddenResponseBody
    | DevLoginNotFoundResponseBody
    | DevLoginInternalServerResponseBody
    | DevLoginBadGatewayResponseBody,
    DevLoginQueryParams,
    DevLoginRequestBody,
    void
  >
    verb="POST"
    path={`/api/login`}
    base={getConfig('ssca/api/v1')}
    {...props}
  />
)

export type UseDevLoginProps = Omit<
  UseMutateProps<
    string,
    | DevLoginBadRequestResponseBody
    | DevLoginUnauthorizedResponseBody
    | DevLoginForbiddenResponseBody
    | DevLoginNotFoundResponseBody
    | DevLoginInternalServerResponseBody
    | DevLoginBadGatewayResponseBody,
    DevLoginQueryParams,
    DevLoginRequestBody,
    void
  >,
  'path' | 'verb'
>

export const useDevLogin = (props: UseDevLoginProps) =>
  useMutate<
    string,
    | DevLoginBadRequestResponseBody
    | DevLoginUnauthorizedResponseBody
    | DevLoginForbiddenResponseBody
    | DevLoginNotFoundResponseBody
    | DevLoginInternalServerResponseBody
    | DevLoginBadGatewayResponseBody,
    DevLoginQueryParams,
    DevLoginRequestBody,
    void
  >('POST', `/api/login`, { base: getConfig('ssca/api/v1'), ...props })

export type SbomprocessorProcesssbomProps = Omit<
  MutateProps<
    void,
    | SbomprocessorProcesssbomBadRequestResponseBody
    | SbomprocessorProcesssbomUnauthorizedResponseBody
    | SbomprocessorProcesssbomForbiddenResponseBody
    | SbomprocessorProcesssbomNotFoundResponseBody
    | SbomprocessorProcesssbomInternalServerResponseBody
    | SbomprocessorProcesssbomBadGatewayResponseBody,
    void,
    SbomprocessorProcesssbomRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * process & inject sbom
 */
export const SbomprocessorProcesssbom = (props: SbomprocessorProcesssbomProps) => (
  <Mutate<
    void,
    | SbomprocessorProcesssbomBadRequestResponseBody
    | SbomprocessorProcesssbomUnauthorizedResponseBody
    | SbomprocessorProcesssbomForbiddenResponseBody
    | SbomprocessorProcesssbomNotFoundResponseBody
    | SbomprocessorProcesssbomInternalServerResponseBody
    | SbomprocessorProcesssbomBadGatewayResponseBody,
    void,
    SbomprocessorProcesssbomRequestBody,
    void
  >
    verb="POST"
    path={`/api/v1/sbomprocessor`}
    base={getConfig('ssca/api/v1')}
    {...props}
  />
)

export type UseSbomprocessorProcesssbomProps = Omit<
  UseMutateProps<
    void,
    | SbomprocessorProcesssbomBadRequestResponseBody
    | SbomprocessorProcesssbomUnauthorizedResponseBody
    | SbomprocessorProcesssbomForbiddenResponseBody
    | SbomprocessorProcesssbomNotFoundResponseBody
    | SbomprocessorProcesssbomInternalServerResponseBody
    | SbomprocessorProcesssbomBadGatewayResponseBody,
    void,
    SbomprocessorProcesssbomRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * process & inject sbom
 */
export const useSbomprocessorProcesssbom = (props: UseSbomprocessorProcesssbomProps) =>
  useMutate<
    void,
    | SbomprocessorProcesssbomBadRequestResponseBody
    | SbomprocessorProcesssbomUnauthorizedResponseBody
    | SbomprocessorProcesssbomForbiddenResponseBody
    | SbomprocessorProcesssbomNotFoundResponseBody
    | SbomprocessorProcesssbomInternalServerResponseBody
    | SbomprocessorProcesssbomBadGatewayResponseBody,
    void,
    SbomprocessorProcesssbomRequestBody,
    void
  >('POST', `/api/v1/sbomprocessor`, { base: getConfig('ssca/api/v1'), ...props })

export interface SearchFindanyQueryParams {
  /**
   * Harness account ID
   */
  accountIdentifier: string
  /**
   * Harness organization ID
   */
  orgIdentifier: string
  /**
   * Harness project ID
   */
  projectIdentifier: string
}

export type SearchFindanyProps = Omit<
  MutateProps<
    SearchFindanyResponseBody,
    | SearchFindanyBadRequestResponseBody
    | SearchFindanyUnauthorizedResponseBody
    | SearchFindanyForbiddenResponseBody
    | SearchFindanyNotFoundResponseBody
    | SearchFindanyInternalServerResponseBody
    | SearchFindanyBadGatewayResponseBody,
    SearchFindanyQueryParams,
    SearchFindanyRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Find a package references by name
 *
 * **Required security scopes for jwt**:
 *   * `core_project_view`
 */
export const SearchFindany = (props: SearchFindanyProps) => (
  <Mutate<
    SearchFindanyResponseBody,
    | SearchFindanyBadRequestResponseBody
    | SearchFindanyUnauthorizedResponseBody
    | SearchFindanyForbiddenResponseBody
    | SearchFindanyNotFoundResponseBody
    | SearchFindanyInternalServerResponseBody
    | SearchFindanyBadGatewayResponseBody,
    SearchFindanyQueryParams,
    SearchFindanyRequestBody,
    void
  >
    verb="POST"
    path={`/api/v1/search/findany`}
    base={getConfig('ssca/api/v1')}
    {...props}
  />
)

export type UseSearchFindanyProps = Omit<
  UseMutateProps<
    SearchFindanyResponseBody,
    | SearchFindanyBadRequestResponseBody
    | SearchFindanyUnauthorizedResponseBody
    | SearchFindanyForbiddenResponseBody
    | SearchFindanyNotFoundResponseBody
    | SearchFindanyInternalServerResponseBody
    | SearchFindanyBadGatewayResponseBody,
    SearchFindanyQueryParams,
    SearchFindanyRequestBody,
    void
  >,
  'path' | 'verb'
>

/**
 * Find a package references by name
 *
 * **Required security scopes for jwt**:
 *   * `core_project_view`
 */
export const useSearchFindany = (props: UseSearchFindanyProps) =>
  useMutate<
    SearchFindanyResponseBody,
    | SearchFindanyBadRequestResponseBody
    | SearchFindanyUnauthorizedResponseBody
    | SearchFindanyForbiddenResponseBody
    | SearchFindanyNotFoundResponseBody
    | SearchFindanyInternalServerResponseBody
    | SearchFindanyBadGatewayResponseBody,
    SearchFindanyQueryParams,
    SearchFindanyRequestBody,
    void
  >('POST', `/api/v1/search/findany`, { base: getConfig('ssca/api/v1'), ...props })

export interface SearchFindQueryParams {
  /**
   * Harness account ID
   */
  accountIdentifier: string
  /**
   * Harness organization ID
   */
  orgIdentifier: string
  /**
   * Harness project ID
   */
  projectIdentifier: string
}

export interface SearchFindPathParams {
  /**
   * Source ID associated with this connection source
   */
  packagename: string
}

export type SearchFindProps = Omit<
  GetProps<
    SearchFindResponseBody,
    | SearchFindBadRequestResponseBody
    | SearchFindUnauthorizedResponseBody
    | SearchFindForbiddenResponseBody
    | SearchFindNotFoundResponseBody
    | SearchFindInternalServerResponseBody
    | SearchFindBadGatewayResponseBody,
    SearchFindQueryParams,
    SearchFindPathParams
  >,
  'path'
> &
  SearchFindPathParams

/**
 * Find a package references by name
 *
 * **Required security scopes for jwt**:
 *   * `core_project_view`
 */
export const SearchFind = ({ packagename, ...props }: SearchFindProps) => (
  <Get<
    SearchFindResponseBody,
    | SearchFindBadRequestResponseBody
    | SearchFindUnauthorizedResponseBody
    | SearchFindForbiddenResponseBody
    | SearchFindNotFoundResponseBody
    | SearchFindInternalServerResponseBody
    | SearchFindBadGatewayResponseBody,
    SearchFindQueryParams,
    SearchFindPathParams
  >
    path={`/api/v1/search/${packagename}`}
    base={getConfig('ssca/api/v1')}
    {...props}
  />
)

export type UseSearchFindProps = Omit<
  UseGetProps<
    SearchFindResponseBody,
    | SearchFindBadRequestResponseBody
    | SearchFindUnauthorizedResponseBody
    | SearchFindForbiddenResponseBody
    | SearchFindNotFoundResponseBody
    | SearchFindInternalServerResponseBody
    | SearchFindBadGatewayResponseBody,
    SearchFindQueryParams,
    SearchFindPathParams
  >,
  'path'
> &
  SearchFindPathParams

/**
 * Find a package references by name
 *
 * **Required security scopes for jwt**:
 *   * `core_project_view`
 */
export const useSearchFind = ({ packagename, ...props }: UseSearchFindProps) =>
  useGet<
    SearchFindResponseBody,
    | SearchFindBadRequestResponseBody
    | SearchFindUnauthorizedResponseBody
    | SearchFindForbiddenResponseBody
    | SearchFindNotFoundResponseBody
    | SearchFindInternalServerResponseBody
    | SearchFindBadGatewayResponseBody,
    SearchFindQueryParams,
    SearchFindPathParams
  >((paramsInPath: SearchFindPathParams) => `/api/v1/search/${paramsInPath.packagename}`, {
    base: getConfig('ssca/api'),
    pathParams: { packagename },
    ...props
  })

export type SystemHealthProps = Omit<
  GetProps<void, SystemHealthInternalServerResponseBody | SystemHealthBadGatewayResponseBody, void, void>,
  'path'
>

/**
 * Check service health
 */
export const SystemHealth = (props: SystemHealthProps) => (
  <Get<void, SystemHealthInternalServerResponseBody | SystemHealthBadGatewayResponseBody, void, void>
    path={`/api/v1/system/health`}
    base={getConfig('ssca/api/v1')}
    {...props}
  />
)

export type UseSystemHealthProps = Omit<
  UseGetProps<void, SystemHealthInternalServerResponseBody | SystemHealthBadGatewayResponseBody, void, void>,
  'path'
>

/**
 * Check service health
 */
export const useSystemHealth = (props: UseSystemHealthProps) =>
  useGet<void, SystemHealthInternalServerResponseBody | SystemHealthBadGatewayResponseBody, void, void>(
    `/api/v1/system/health`,
    { base: getConfig('ssca/api/v1'), ...props }
  )

export type SystemVersionProps = Omit<
  GetProps<
    SystemVersionResponseBody,
    SystemVersionInternalServerResponseBody | SystemVersionBadGatewayResponseBody,
    void,
    void
  >,
  'path'
>

/**
 * Check service version
 */
export const SystemVersion = (props: SystemVersionProps) => (
  <Get<
    SystemVersionResponseBody,
    SystemVersionInternalServerResponseBody | SystemVersionBadGatewayResponseBody,
    void,
    void
  >
    path={`/api/v1/system/version`}
    base={getConfig('ssca/api/v1')}
    {...props}
  />
)

export type UseSystemVersionProps = Omit<
  UseGetProps<
    SystemVersionResponseBody,
    SystemVersionInternalServerResponseBody | SystemVersionBadGatewayResponseBody,
    void,
    void
  >,
  'path'
>

/**
 * Check service version
 */
export const useSystemVersion = (props: UseSystemVersionProps) =>
  useGet<
    SystemVersionResponseBody,
    SystemVersionInternalServerResponseBody | SystemVersionBadGatewayResponseBody,
    void,
    void
  >(`/api/v1/system/version`, { base: getConfig('ssca/api/v1'), ...props })
