/*
 * Copyright 2023 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useQuery, UseQueryOptions } from '@tanstack/react-query'

import type { ResponseTemplateResponse } from '../schemas/ResponseTemplateResponse'
import type { Failure } from '../schemas/Failure'
import type { Error } from '../schemas/Error'
import { fetcher, FetcherOptions } from 'services/fetcher'

export interface GetTemplateQueryPathParams {
  templateIdentifier: string
}

export interface GetTemplateQueryQueryParams {
  accountIdentifier: string
  orgIdentifier?: string
  projectIdentifier?: string
  versionLabel?: string
  deleted?: boolean
  branch?: string
  repoIdentifier?: string
  getDefaultFromOtherRepo?: boolean
  parentEntityConnectorRef?: string
  parentEntityRepoName?: string
  parentEntityAccountIdentifier?: string
  parentEntityOrgIdentifier?: string
  parentEntityProjectIdentifier?: string
  repoName?: string
  loadFromFallbackBranch?: boolean
}

export type GetTemplateOkResponse = ResponseTemplateResponse

export type GetTemplateErrorResponse = Failure | Error

export interface GetTemplateProps
  extends GetTemplateQueryPathParams,
    Omit<FetcherOptions<GetTemplateQueryQueryParams, unknown>, 'url'> {
  queryParams: GetTemplateQueryQueryParams
}

export function getTemplate(props: GetTemplateProps): Promise<GetTemplateOkResponse> {
  const { templateIdentifier, ...rest } = props

  return fetcher<GetTemplateOkResponse, GetTemplateQueryQueryParams, unknown>({
    url: `template/api/templates/${templateIdentifier}`,
    method: 'GET',
    ...rest
  })
}

/**
 *
 */
export function useGetTemplateQuery(
  props: GetTemplateProps,
  options?: Omit<UseQueryOptions<GetTemplateOkResponse, GetTemplateErrorResponse>, 'queryKey' | 'queryFn'>
) {
  return useQuery<GetTemplateOkResponse, GetTemplateErrorResponse>(
    ['getTemplate', props.templateIdentifier, props.queryParams],
    ({ signal }) => getTemplate({ ...props, signal }),
    options
  )
}
