/*
 * Copyright 2023 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useQuery, UseQueryOptions } from '@tanstack/react-query'

import type { ResponseString } from '../schemas/ResponseString'
import type { Failure } from '../schemas/Failure'
import type { Error } from '../schemas/Error'
import { fetcher, FetcherOptions } from 'services/fetcher'

export interface GetTemplateInputSetYamlQueryPathParams {
  templateIdentifier: string
}

export interface GetTemplateInputSetYamlQueryQueryParams {
  accountIdentifier: string
  orgIdentifier?: string
  projectIdentifier?: string
  versionLabel: string
  branch?: string
  repoIdentifier?: string
  getDefaultFromOtherRepo?: boolean
  parentEntityConnectorRef?: string
  parentEntityRepoName?: string
  parentEntityAccountIdentifier?: string
  parentEntityOrgIdentifier?: string
  parentEntityProjectIdentifier?: string
  repoName?: string
}

export type GetTemplateInputSetYamlOkResponse = ResponseString

export type GetTemplateInputSetYamlErrorResponse = Failure | Error

export interface GetTemplateInputSetYamlProps
  extends GetTemplateInputSetYamlQueryPathParams,
    Omit<FetcherOptions<GetTemplateInputSetYamlQueryQueryParams, unknown>, 'url'> {
  queryParams: GetTemplateInputSetYamlQueryQueryParams
}

export function getTemplateInputSetYaml(
  props: GetTemplateInputSetYamlProps
): Promise<GetTemplateInputSetYamlOkResponse> {
  const { templateIdentifier, ...rest } = props

  return fetcher<GetTemplateInputSetYamlOkResponse, GetTemplateInputSetYamlQueryQueryParams, unknown>({
    url: `template/api/templates/templateInputs/${templateIdentifier}`,
    method: 'GET',
    ...rest
  })
}

/**
 *
 */
export function useGetTemplateInputSetYamlQuery(
  props: GetTemplateInputSetYamlProps,
  options?: Omit<
    UseQueryOptions<GetTemplateInputSetYamlOkResponse, GetTemplateInputSetYamlErrorResponse>,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery<GetTemplateInputSetYamlOkResponse, GetTemplateInputSetYamlErrorResponse>(
    ['getTemplateInputSetYaml', props.templateIdentifier, props.queryParams],
    ({ signal }) => getTemplateInputSetYaml({ ...props, signal }),
    options
  )
}
