kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: archittest
apiVersion: backstage.io/v1alpha1
metadata:
  name: Archit-archittest-newservice
  tags: []
  annotations:
    harness.io/cd-serviceId: newservice
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/Archit/projects/archittest/details

