kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: KapilTestProject
apiVersion: backstage.io/v1alpha1
metadata:
  name: default-KapilTestProject-asd
  tags: []
  annotations:
    harness.io/cd-serviceId: asd
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/default/projects/KapilTestProject/details

