kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: mouniktest
apiVersion: backstage.io/v1alpha1
metadata:
  name: default-mouniktest-Service1
  tags: []
  annotations:
    harness.io/cd-serviceId: Service1
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/default/projects/mouniktest/details

