kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: DevXGitSyncPro4FQy
apiVersion: backstage.io/v1alpha1
metadata:
  name: sadf
  tags: []
  annotations:
    harness.io/cd-serviceId: sadf
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/DevXGitSyncOrgwTby/projects/DevXGitSyncPro4FQy/details

