kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: sam_rollback_tests
apiVersion: backstage.io/v1alpha1
metadata:
  name: ser3
  tags: []
  annotations:
    harness.io/cd-serviceId: ser3
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/default/projects/sam_rollback_tests/details

