/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
import type * as Schemas from './portalSchemas'

export type BuildDetails = Schemas.BuildDetails

export type CustomSecretsManagerConfig = Schemas.CustomSecretsManagerConfig

export type Preference = Schemas.Preference

export type LogMLFeedback = Schemas.LogMLFeedback

export type FailureStrategyArray = Schemas.FailureStrategy[]

export type PatchRequest = Schemas.PatchRequest

export type HelmChartSpecification = Schemas.HelmChartSpecification

export type DelegateProfileDetails = Schemas.DelegateProfileDetails

export type TemplateFolder = Schemas.TemplateFolder

export type DelegateResponseData = Schemas.DelegateResponseData

export type NotificationGroup = Schemas.NotificationGroup

export type UserGroup = Schemas.UserGroup

export type ViewCustomField = Schemas.ViewCustomField

export type ModuleLicenseDTO = Schemas.ModuleLicenseDTO

export type ApplicationManifest = Schemas.ApplicationManifest

export type KubernetesPayload = Schemas.KubernetesPayload

export type ApiKeyEntry = Schemas.ApiKeyEntry

export type DelegateScopes = Schemas.DelegateScopes

export type ArtifactStreamBinding = Schemas.ArtifactStreamBinding

export type ManifestFile = Schemas.ManifestFile

export type VaultConfig = Schemas.VaultConfig

export type InfrastructureProvisioner = Schemas.InfrastructureProvisioner

export type UserInvite = Schemas.UserInvite

export type LicenseInfo = Schemas.LicenseInfo

export type Whitelist = Schemas.Whitelist

export type InfrastructureMapping = Schemas.InfrastructureMapping

export type ValidateBody = string

export type TemplateGallery = Schemas.TemplateGallery

export type Template = Schemas.Template

export type AlertNotificationRule = Schemas.AlertNotificationRule

export type CVConfiguration = Schemas.CVConfiguration

export type InfrastructureDefinition = Schemas.InfrastructureDefinition

export type UpdateAccountPreferenceBody = Record<string, any>

export type TaskSelectorMap = Schemas.TaskSelectorMap

export type PhaseStep = Schemas.PhaseStep

export type YamlGitConfig = Schemas.YamlGitConfig

export type SplunkConnectorDTO = Schemas.SplunkConnectorDTO

export type SwitchAccountRequest = Schemas.SwitchAccountRequest

export type EcsServiceSpecification = Schemas.EcsServiceSpecification

export type Delegate = Schemas.Delegate

export type LdapSettings = Schemas.LdapSettings

export type CVFeedbackRecord = Schemas.CVFeedbackRecord

export type Service = Schemas.Service

export type Trigger = Schemas.Trigger

export type ServiceTemplate = Schemas.ServiceTemplate

export type DelegateGroupDetails = Schemas.DelegateGroupDetails

export type GcpOrganization = Schemas.GcpOrganization

export type Budget = Schemas.Budget

export type KmsConfig = Schemas.KmsConfig

export type Artifact = Schemas.Artifact

export type Application = Schemas.Application

export type WorkflowPhase = Schemas.WorkflowPhase

export type AccessRequestDTO = Schemas.AccessRequestDTO

export type UpdateWhitelistedDomainsBody = string[]

export type Account = Schemas.Account

export type ArtifactStream = Schemas.ArtifactStream

export type CEReportSchedule = Schemas.CEReportSchedule

export type CgEventConfig = Schemas.CgEventConfig

export type DelegateParams = Schemas.DelegateParams

export type GetDelegatePropertiesBody = string[]

export type DelegateProfile = Schemas.DelegateProfile

export type DelegateScope = Schemas.DelegateScope

export type DelegateTags = Schemas.DelegateTags

export type DelegateSetupDetails = Schemas.DelegateSetupDetails

export type Environment = Schemas.Environment

export type CloneMetadata = Schemas.CloneMetadata

export type ExecutionArgs = Schemas.ExecutionArgs

export type SaveMessageComparisonListBody = {
  [key: string]: string
}

export type GcpBillingAccount = Schemas.GcpBillingAccount

export type HarnessTagLink = Schemas.HarnessTagLink

export type HarnessTag = Schemas.HarnessTag

export type HarnessUserGroupDTO = Schemas.HarnessUserGroupDTO

export type Pipeline = Schemas.Pipeline

export type ResourceConstraint = Schemas.ResourceConstraint

export type Role = Schemas.Role

export type LDAPTestAuthenticationRequest = Schemas.LDAPTestAuthenticationRequest

export type OauthSettings = Schemas.OauthSettings

export type ScimGroup = Schemas.ScimGroup

export type ScimUser = Schemas.ScimUser

export type ServiceCommand = Schemas.ServiceCommand

export type PcfServiceSpecification = Schemas.PcfServiceSpecification

export type ContainerTask = Schemas.ContainerTask

export type LambdaSpecification = Schemas.LambdaSpecification

export type UserDataSpecification = Schemas.UserDataSpecification

export type ServiceVariable = Schemas.ServiceVariable

export type SettingAttribute = Schemas.SettingAttribute

export type StackDriverSetupTestNodeData = Schemas.StackDriverSetupTestNodeData

export type User = Schemas.User

export type LoginRequest = Schemas.LoginRequest

export type WebHookRequest = Schemas.WebHookRequest

export type Workflow = Schemas.Workflow

export type ContinuousVerificationAlertData = Schemas.ContinuousVerificationAlertData

export type K8sEventCollectionBundle = Schemas.K8sEventCollectionBundle

export type DataCollectionConnectorBundle = Schemas.DataCollectionConnectorBundle

export type DashboardSettings = Schemas.DashboardSettings

export type AzureVaultConfig = Schemas.AzureVaultConfig

export type SSHVaultConfig = Schemas.SSHVaultConfig

export type SecretText = Schemas.SecretText

export type CEView = Schemas.CEView

export type YamlPayload = Schemas.YamlPayload
