rules:
  no-restricted-imports:
    - error
    - patterns:
        - group:
            - lodash/*
            - lodash.*
            - lodash-es/*
            - '!lodash/fp'
          message: Import from 'lodash-es' instead
        - group:
            - microfrontends/*
            - '!microfrontends/ChildAppMounter'
      paths:
        - lodash
        - name: js-yaml
          message: Please use methods from @common/utils/YamlHelperMethods instead of using js-yaml
        - name: yaml
          importNames:
            - stringify
          message: Please use yamlStringify from @common/utils/YamlHelperMethods instead of this
        - name: react-router
          message: import from "react-router-dom" instead
        - name: microfrontends
          message: Import from 'microfrontends' is only allowed in child apps
        - name: '@wings-software/uicore'
          importNames:
            - Color
            - FontVariation
            - Intent
            - Spacing
          message: import from "@harness/design-system" instead
