kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: vbnongitsync
apiVersion: backstage.io/v1alpha1
metadata:
  name: default-vbnongitsync-svc
  tags: []
  annotations:
    harness.io/cd-serviceId: svc
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/default/projects/vbnongitsync/details

