kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: mvtesttemplates
apiVersion: backstage.io/v1alpha1
metadata:
  name: helloworld
  tags: []
  annotations:
    harness.io/cd-serviceId: helloworld
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/default/projects/mvtesttemplates/details

