kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: SSCA
apiVersion: backstage.io/v1alpha1
metadata:
  name: hi
  tags: []
  annotations:
    harness.io/cd-serviceId: hi
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/default/projects/SSCA/details

