kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: Chirag
apiVersion: backstage.io/v1alpha1
metadata:
  name: new2323
  tags: []
  annotations:
    harness.io/cd-serviceId: new2323
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/harness/projects/Chirag/details

