kind: Component
spec:
  type: Service
  lifecycle: Unknown
  owner: Unknown
  system: ECS_Sainath
apiVersion: backstage.io/v1alpha1
metadata:
  name: Sainath_ECS_Sample_Service_2
  tags: []
  annotations:
    harness.io/cd-serviceId: Sainath_ECS_Sample_Service_2
    harness.io/project-url-stress: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/default/projects/ECS_Sainath/details

