apiVersion: v1
kind: ConfigMap
metadata:
  name: ui
  namespace: {{ .Release.Namespace }}
data:
  API_URL: '{{ .Values.global.loadbalancerURL }}/gateway'
  HARNESS_ENABLE_DRIFT_PLACEHOLDER: "false"
  HARNESS_ENABLE_NG_AUTH_UI_PLACEHOLDER: "true"
  {{- if .Values.global.airgap }}
  HARNESS_ENABLE_EXTERNAL_SCRIPTS_PLACEHOLDER: "false"
  HARNESS_ENABLE_SABERFEEDBACK_PLACEHOLDER: "false"
  HARNESS_ENABLE_MUNCHKIN_PLACEHOLDER: "false"
  HARNESS_ENABLE_AMPLITUDE_PLACEHOLDER: "false"
  HARNESS_ENABLE_ELEVIO_PLACEHOLDER: "false"
  HARNESS_ENABLE_GOOGLEANALYTICS_PLACEHOLDER: "false"
  HARNESS_ENABLE_GET_IP_ADDRESS_PLACEHOLDER: "false"
  HARNESS_ENABLE_BUGSNAG_PLACEHOLDER: "false"
  HARNESS_ENABLE_HEADWAY_PLACEHOLDER: "false"
  HARNESS_ENABLE_SEGMENT_PLACEHOLDER: "false"
  HARNESS_ENABLE_APPDY_EUM_PLACEHOLDER: "false"
  {{ end }}
