apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ui.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "ui.selectorLabels" . | nindent 6 }}
